Bugfix: regexp matches are strings until converted.
2025-11-05 10:02:45,565 N=ytffmpeg.cli.refresh F=detectSilence PID=18448 DEBUG: Using silence threshold: -30dB, duration: 1.2s
Traceback (most recent call last):
  File "/usr/local/bin/ytffmpeg", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ytffmpeg/__init__.py", line 23, in main
    ytffmpeg.execute()
  File "/usr/local/lib/python3.11/dist-packages/ytffmpeg/cli/__init__.py", line 179, in execute
    return action(self.config)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ytffmpeg/cli/refresh.py", line 566, in refresher
    return cmd.execute()
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ytffmpeg/cli/refresh.py", line 487, in execute
    processed_resource = self.removeSilence(resource)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ytffmpeg/cli/refresh.py", line 216, in removeSilence
    silence_filters = self.detectSilence(resource)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ytffmpeg/cli/refresh.py", line 146, in detectSilence
    silence_starts = [float(round(match, 3)) for match in re.findall(silence_start_pattern, output)]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ytffmpeg/cli/refresh.py", line 146, in <listcomp>
    silence_starts = [float(round(match, 3)) for match in re.findall(silence_start_pattern, output)]
                            ^^^^^^^^^^^^^^^
TypeError: type str doesn't define __round__ method